name: ✨ Feature Request
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["feature", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature!

        Please describe the feature and why it would be valuable.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: I'm frustrated when... / I need to... / Users are asking for...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: I considered... / Another approach would be...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High (blocking my work)
        - Medium (would be very helpful)
        - Low (nice to have)
    validations:
      required: true

  - type: checkboxes
    id: areas
    attributes:
      label: Area
      description: Which areas does this feature affect? (Select all that apply)
      options:
        - label: Frontend
        - label: Backend
        - label: API
        - label: Infrastructure
        - label: CI/CD
        - label: Documentation
        - label: Developer Experience
        - label: Security
        - label: Performance

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, screenshots, or examples
      placeholder: Drag and drop images or links here...

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details, dependencies, or constraints to consider?
      placeholder: This would require... / Depends on... / Impacts...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or information
      placeholder: Related to... / Similar to... / Inspired by...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I'm willing to help test this feature
        - label: I can provide design/UX input

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have checked the roadmap and documentation
          required: true
        - label: I have provided all required information
          required: true
